# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fd2cf8077e06d54faa3e6874e88520bbf5e1e324284e1361ae6b947d80d7f147bc6cadd403495f4b88a4b712d2248705e3c7672d78080cf2f53d8e5957ae7f8

test:
  secret_key_base: 7dfdac5ee57b12e7fefca87dd5f80fae2a4f1c36cd68ecc44840449046d45d822662620286c714aa15ee5ccff315487694516fd0ee0748aff09c571b84c1b4c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
